version: "2.2"

networks:
  default:
  frontend:
    name: frontend

services:
  minio:
    image: minio/minio:latest
    restart: always
    command:
      - server
      - /data
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-minio.rule=Host(`minio.${DOMAIN_SECONDARY}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-minio.loadbalancer.server.port=9000
    networks:
      - default
      - frontend
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-miniostorage}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME:-us-east-1}
    volumes:
      - ${PATH_DATA:-./data}/minio:/data
