version: "2.2"

networks:
  default:
  frontend:
    name: frontend

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN_SECONDARY}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-phpmyadmin.loadbalancer.server.port=80
    networks:
      - default
      - frontend
    environment:
      - PMA_HOSTS=mysql,mysql-test,mariadb
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
